---
- hosts: localhost
  become: yes
  roles:
  - role: base
    tags: base
  - role: boot
    tags: boot
  - role: audio
    tags: audio
  - role: backlight
    tags: backlight
  - role: apps
    tags: apps
  - role: gc-controller
    tags: gc-controller
