---
- hosts: localhost
  become: yes
  roles:
  - boot
  - locale
  - timezone
  - base
  - network
  - user
  - audio
  - video
  - music
  - desktop
  - dev-ops
  - steam
  - emulation
#  vars_prompt:
#  - name: user_password
#    prompt: Enter desired user password
