---
- hosts: localhost
  become: yes
  roles:
  - boot
  - locale
  - timezone
  - base
  - user
  - audio
  - video
  - desktop
  - steam
#  vars_prompt:
#  - name: user_password
#    prompt: Enter desired user password
