---
- name: Install desktop packages
  pacman:
    name: "{{ packages.desktop }}"
    state: present

- name: Install desktop packages (AUR)
  aur:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items: "{{ packages.desktop_aur }}"

- name: Install fonts
  pacman:
    name: "{{ packages.fonts }}"
    state: present
